### ISSUE TITLE
No module named 'corsheaders'

### ISSUE THREAD

**Issue by datatalking** [Jordanirabor/django-todo-react#5]
I've followed the instructions and terminal is generating errors.

To troubleshoot: I brew upgrade node and this is still generating code errors.

I must say the rest of the install went like a dream.

$ python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10e86bd90>
Traceback (most recent call last):
  File "/Users/owner/.local/share/virtualenvs/django-todo-react-EZhWWSJP/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/owner/.local/share/virtualenvs/django-todo-react-EZhWWSJP/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Users/owner/.local/share/virtualenvs/django-todo-react-EZhWWSJP/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/Users/owner/.local/share/virtualenvs/django-todo-react-EZhWWSJP/lib/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/owner/.local/share/virtualenvs/django-todo-react-EZhWWSJP/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/owner/.local/share/virtualenvs/django-todo-react-EZhWWSJP/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/owner/.local/share/virtualenvs/django-todo-react-EZhWWSJP/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/Users/owner/.local/share/virtualenvs/django-todo-react-EZhWWSJP/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/owner/.local/share/virtualenvs/django-todo-react-EZhWWSJP/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'corsheaders'

**Comment by saeeddawod** [comment]
try pipenv install django-cors-headers
